#pragma once

#define PHY_TIMER_INTERVAL (20)

#define PHY_MODE_3D (0)
#define PHY_MODE_2D (1)

#define PHY_ROLLING_MODE_DEFAULT    (0)
#define PHY_ROLLING_MODE_ADVANCED   (1)

#define FLOAT_INFINITY       (0x7F800000)
#define FLOAT_NEG_INFINITY   (0xFF800000)
#define FLOAT_NAN	         (0xFFFFFFFF)

enum
{
	PHY_ITEM_OBJECT,
	PHY_ITEM_WALL,
    PHY_ITEM_CYLINDER,

    PHY_MAX_ITEM_TYPES
};

enum PHY_OBJECT_FLAGS {
    PHY_OBJECT_USED = 1,
    PHY_OBJECT_MODE = 1 << 1,
    PHY_OBJECT_ROLL = 1 << 2,
    PHY_OBJECT_ROLLING_MODE = 1 << 3,
    PHY_OBJECT_COLANDREAS_BOUNDS = 1 << 4,
    PHY_OBJECT_COLANDREAS_COLLS = 1 << 5,
    PHY_OBJECT_GHOST_OBJECTS = 1 << 6,
    PHY_OBJECT_GHOST_WALLS = 1 << 7,
    PHY_OBJECT_GHOST_CYLINDERS = 1 << 8,
    PHY_OBJECT_PLAYER_COLLISIONS = 1 << 9
};